### ISSUE TITLE
Strange class names in auto completion

### ISSUE THREAD

**Issue by PhaserEditor2D** [angelozerr/tern-phaser#10]
In the online demor if I press CTRL+SPACE I get strange class names like <anonymous>~AABB

![image](https://cloud.githubusercontent.com/assets/12187299/9940458/0d540a30-5d3e-11e5-96d6-8ad3156fed95.png)

**Comment by angelozerr** [comment]
Yes I have seen that. It's JSDoc which contains that. I must study what it is mean.
