### ISSUE TITLE
Auto-completion is not including the declaring type

### ISSUE THREAD

**Issue by PhaserEditor2D** [angelozerr/tern-phaser#11]
In this image you can see the completion popup on shows the name of the members, but not the declaring type. This is something that happens also in the Tern IDE:

![image](https://cloud.githubusercontent.com/assets/12187299/9959203/ef9fea52-5ddf-11e5-86c4-473a786b3007.png)

It will be nice to see a popup like:

```
helloA() - A
helloB() - B
```

**Comment by angelozerr** [comment]
I close this issue because it's not related to tern-phaser. Please create your issue at https://github.com/angelozerr/CodeMirror-JavaScript/issues
