### ISSUE TITLE
please add brackets .tern-project file and instruction to use brackets.

### ISSUE THREAD

**Issue by pooya72** [angelozerr/tern-phaser#12]

**Comment by angelozerr** [comment]
I can explain how to fill .tern-project but I don't know for bracket. Sorry I cannot help you with that, please post your issue to bracket, thanks.

**Comment by pooya72** [comment]
so please explain how to fill .tern-project, Thx

**Comment by pooya72** [comment]
are you planning to make one ?

**Comment by angelozerr** [comment]
> are you planning to make one ?

Please read https://github.com/angelozerr/tern-phaser#-installation and https://github.com/angelozerr/tern-phaser#-configuration

For Bracket, please help me to fill https://github.com/angelozerr/tern-phaser/blob/master/INSTALL.md#bracket

Thanks

**Comment by pooya72** [comment]
I do have difficulty in creating one for myself but this link may help you

http://www.netsi.dk/wordpress/index.php/2015/06/17/my-brackets-just-got-meteor-autosuggest/

—

**Comment by angelozerr** [comment]
Yes I have seen that now, I have added to the INSTALL.

**Comment by angelozerr** [comment]
Can you use tern phaser with brackets?

**Comment by pooya72** [comment]
No i cant and don't know where is the problem

—

**Comment by angelozerr** [comment]
> No i cant and don't know where is the problem

That's shame -(

Perhaps you should create issue https://github.com/MiguelCastillo/Brackets-Ternific to have some help. If you can use tern phaser with brackets, please explain us how you have done that. Thanks
