### ISSUE TITLE
Missing Phaser constants

### ISSUE THREAD

**Issue by PhaserEditor2D** [angelozerr/tern-phaser#2]
The Phaser namespace has global constants like Phaser.AUTO, Phaser.WEBGL, etc....
These constants are not displayed in the online demo.

The Phaser.Keyboard constants are missing too, like Phaser.Keyboard.ALT.

**Comment by angelozerr** [comment]
Yes I have seen that, but my problem is about JSDoc. If you see the generated json JSDoc https://github.com/angelozerr/tern-phaser/blob/master/generator/data/jsdoc-ast.json from the Phaser source :

``` json
{
        "comment": "/**\n    * AUTO renderer - picks between WebGL or Canvas based on device.\n    * @constant\n    * @type {integer}\n    */",
        "meta": {
            "range": [
                618,
                625
            ],
            "filename": "Phaser.js",
            "lineno": 32,
            "path": "C:\\Users\\azerr\\git\\phaser\\src",
            "code": {
                "id": "astnode100129194",
                "name": "AUTO",
                "type": "Literal",
                "value": 0
            }
        },
        "description": "AUTO renderer - picks between WebGL or Canvas based on device.",
        "kind": "constant",
        "type": {
            "names": [
                "integer"
            ]
        },
        "name": "AUTO",
        "longname": "AUTO",
        "scope": "global"
    }
```

It defines a global constant, but I have none indormation that this constants belongs to Phaser object (it misses memberof, why?)?

Have you an idea about that? Perhaps the solution is to hard coded that (set those global constants to Phaser).

For other constant like 

``` javascript
/**
* @constant
* @type {number}
*/
Phaser.Camera.FOLLOW_TOPDOWN = 2;
```

The JSDoc is 

``` json
{
        "comment": "/**\n* @constant\n* @type {number}\n*/",
        "meta": {
            "range": [
                4462,
                4494
            ],
            "filename": "Camera.js",
            "lineno": 138,
            "path": "C:\\Users\\azerr\\git\\phaser\\src\\core",
            "code": {
                "id": "astnode100034096",
                "name": "Phaser.Camera.FOLLOW_TOPDOWN",
                "type": "Literal",
                "value": 2,
                "paramnames": []
            }
        },
        "kind": "constant",
        "type": {
            "names": [
                "number"
            ]
        },
        "name": "FOLLOW_TOPDOWN",
        "longname": "Phaser.Camera.FOLLOW_TOPDOWN",
        "memberof": "Phaser.Camera",
        "scope": "static"
    }
```

I can use the memberof information to know that FOLLOW_TOPDOWN belongs to Camera.

**Comment by PhaserEditor2D** [comment]
> It defines a global constant, but I have none indormation that this constants belongs to Phaser object > (it misses memberof, why?)?

Because the @memberof tag is missing in the jsdoc of Phaser.js:

https://github.com/photonstorm/phaser/blob/master/src/Phaser.js

Yes, in my editor I assume al global constants are in the Phaser namespace. The other solution is to do a pull request to the Phaser repo and fix the jsdoc.

Look in the Camera.js file the constants are written in other way:

https://github.com/photonstorm/phaser/blob/master/src/core/Camera.js

``` javascript
Phaser.Camera.FOLLOW_PLATFORMER = 1;
```

**Comment by PhaserEditor2D** [comment]
Change the Phaser code can be a slow process (we have to wait for a release), the other option is to tweak the jsdoc template, not the tern jsdoc parser.

**Comment by angelozerr** [comment]
Thanks @boniatillo-com I have tweeked the JSDoc to fix this issue.
