### ISSUE TITLE
JSDoc tag @type is not working in the online demo

### ISSUE THREAD

**Issue by PhaserEditor2D** [angelozerr/tern-phaser#9]
``` javascript
/**
 * @type Phaser.Game
 */
var game;

game.<missing auto-completion>
```

The declaration of a type via JSDoc is important because there are cases where the type cannot be inferred, so the @type is used to "cast" to a specific type.

**Comment by angelozerr** [comment]
It's the same issue than https://github.com/angelozerr/tern-phaser/issues/8 the doc_comment.js tern plugin which provides JSDoc support was added to the demo.

**Comment by PhaserEditor2D** [comment]
great! this tern thing works really fine :)

**Comment by angelozerr** [comment]
> great! this tern thing works really fine :)

ternjs is so wonderfull, I love so it and I hope you too you will love it:)
